import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import Sidebar from '@/components/sidebar/sidebar';
import { Toaster } from "@/components/ui/sonner"
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='min-h-screen bg-[#f1f1f1] lg:grid lg:grid-cols-[1fr_7fr]'>
          <Sidebar />
          <div className='lg:col-start-2'>
            <Navbar />
            <div className='py-4 px-6'>
              {children}

            </div>
          </div>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
